apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-c
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-c
    spec:
      containers:
      - name: frontend-c
        image: docker.io/pabsaguilar2806/frontend:latest
        ports:
        - containerPort: 4200
          name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-c
spec:
  type: LoadBalancer
  ports:
  - port: 4200
  selector:
    app: frontend-c