version: '2'
services:
  angular: # name of the first service
    build: FrontEnd # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
      
  redis: # name of the third service
    image: redis # specify image to build container from
    expose: 
        - 3679
  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
       - database 
       - redis
    environment:
    - REDIS_URL=redis://redis
    - Mongo_URL=mongodb://database:27017/store