apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: express
  name: express
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: express
    spec:
      containers:
      - env:
        - name: Mongo_URL
          value: mongodb://database:27017/store
        - name: REDIS_URL
          value: redis://redis
        image: express
        name: express
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
