apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-c
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-c
    spec:
      containers:
      - name: backend-c
        image: docker.io/pabsaguilar2806/backend:latest
        ports:
        - containerPort: 3000
          name: backend
        env:
          - name: Mongo_URL
            value: mongodb://10.0.90.46:27017/store
          - name: REDIS_URL
            value: redis://10.0.201.233
---
apiVersion: v1
kind: Service
metadata:
  name: backend-c
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: backend-c