apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-c
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-c
    spec:
      containers:
      - name: mongo-c
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-c
spec:
  ports:
  - port: 27017
  selector:
    app: mongo-c
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-c
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-c
    spec:
      containers:
      - name: redis-c
        image: redis
        ports:
        - containerPort: 3679
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-c
spec:
  ports:
  - port: 3679
  selector:
    app: redis-c